<html>
 <head>
   <title>Hello World</title>
 </head>
 <body>
    <?php echo "hello world generated by php!";?><br />
    <?php echo $_SERVER['QUERY_STRING']; ?><br />
    <?php echo var_dump($_POST); ?>
    <?php

    if (!empty($_POST))
    {
      echo "not empty";
    }
    else
    {
      echo "empty";
    }
    ?>
 </body>
</html>